name: 05 - 1 - Event Filters and Activity Types.

on:
  pull_request:
    type:
      - opened
      - synchronized
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run : echo "Running whenevr the PR is opened or synchronized AND base branch is master"
